import type { Metadata } from "next";
import { AuthProvider } from "@/lib/supabase/provider";
import { Nav } from "@/components/ui/nav";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";

export const metadata: Metadata = {
  title: "Series Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi">
      <body>
        <AuthProvider>
          <Nav />
          {children}
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
